### PR TITLE
adding `construct_report_listing()`

### PR DESCRIPTION
**Pull request by ddsjoberg**
@shannonpileggi this is the helper function we've spoken about in the past. it's not the world's best API, but a place to start a conversation.

``` r
library(affirm) |> suppressPackageStartupMessages()

# return columns am and cyl; add new column with affirmation label
construct_report_listing(
  rows = .data$am == 1 | !.env$lgl_condition,
  columns = c(am, cyl), 
  label = TRUE
)
#> <quosure>
#> expr: ^dplyr::filter(., .data$am == 1 | !.env$lgl_condition) %>% dplyr::select(
#>           c(am, cyl)) %>% mutate(..label.. = label)
#> env:  global

affirm_init(replace = TRUE)
#> ✔ We're ready to make data affirmations...
as_tibble(mtcars) |>
  affirm_true(
    label = "No. cylinders must be 4 or 6",
    condition = cyl %in% c(4, 6),
    report_listing = 
      !!construct_report_listing(
        rows = .data$am == 1 | !.env$lgl_condition,
        columns = c(am, cyl), 
        label = TRUE
      )
  ) |> 
  invisible()
#> • No. cylinders must be 4 or 6
#>   14 issues identified.

affirm_report_raw_data()$data
#> [[1]]
#> # A tibble: 25 × 3
#>       am   cyl ..label..                   
#>    <dbl> <dbl> <chr>                       
#>  1     1     6 No. cylinders must be 4 or 6
#>  2     1     6 No. cylinders must be 4 or 6
#>  3     1     4 No. cylinders must be 4 or 6
#>  4     0     8 No. cylinders must be 4 or 6
#>  5     0     8 No. cylinders must be 4 or 6
#>  6     0     8 No. cylinders must be 4 or 6
#>  7     0     8 No. cylinders must be 4 or 6
#>  8     0     8 No. cylinders must be 4 or 6
#>  9     0     8 No. cylinders must be 4 or 6
#> 10     0     8 No. cylinders must be 4 or 6
#> # ℹ 15 more rows
```

<sup>Created on 2023-06-17 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### CODE REVIEW

**Comment by shannonpileggi** [comment]
oh my i totally forgot about this one! 😳 maybe we should chat about it?

**Comment by ddsjoberg** [comment]
> oh my i totally forgot about this one! 😳 maybe we should chat about it?

Haha, i forgot everything about it too!

**Comment by ddsjoberg** [comment]
since neither of us know what this PR was meant to do, shall we close it? @shannonpileggi

**Comment by shannonpileggi** [comment]
agreed

**Pull request closed without merging**
